# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: notpassword
    ports:
      - 5432:5432
    volumes:
      - "../data:/csv/data"
      - "./myinit.sql:/docker-entrypoint-initdb.d/myinit.sql"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080